### PR TITLE
Upgrade chart

### PR DESCRIPTION
**Pull request by rsyabuta**
Upgrade the chart to the latest version

### CODE REVIEW

**Comment by himadrisingh** [comment]
should we rebase master first as there are way too many changes to review.

**Comment by rsyabuta** [comment]
This PR is a rebase of master.

**Comment by rsyabuta** [comment]
https://help.github.com/en/articles/syncing-a-fork

**Review by himadrisingh — APPROVED** [review]
ah ok, so no custom changes.

**Pull request merged**
